model:
  provider: Vertex
  name: gemini-2.5-pro
  max_tokens: 100000

task: information_extraction

nepabench_directory: ./nepabench

benchmark:
  input_file: EISBench/benchmark.json
  field_mapping:
    file_name: file_name
    field_type: type
    chunks_json: json_file
    entry_id: entry_id
    field_name: field
    description: description
    answer: answer
    page_number: page_number

evaluation:
  prompt_file: 'prompts/eisie_prompt.txt'
  continue_previous: true
  eval_kwargs:
    max_attempts: 10
    retry_delay: 10

scoring:
  metrics_config: "metrics/eis_metrics.json"

output:
  directory: 'results/nepabench_tests/eis_gemini/'
  logfile: 'logs/nepabench_tests/eis_gemini.log'
