model:
  provider: Vertex
  name: gemini-2.5-pro
  max_tokens: 100000

task: question_answer

nepabench_directory: ./nepabench

benchmark:
  input_file: 'nepaquad/benchmark.json'
  field_mapping:
    question: question
    answer: answer
    file_name: file_name
    chunks_json: json_file
    context: context
    question_type: question_type 
  question_types:
    - closed
    - evaluation
  
evaluation:
  prompt_file: 'prompts/no_context.txt'
  continue_previous: true
  eval_kwargs:
    context_type: none
    max_attempts: 10

scoring:
  batch_size: 4
  embed_model_name: 'all-MiniLM-L6-v2'
  metrics:
    - answer_correctness
    - answer_similarity

output:
  directory: 'results/nepabench_tests/qa_none_gemini/'
  logfile: 'logs/nepabench_tests/qa_none_gemini.log'
