model:
  provider: Vertex
  name: gemini-2.5-pro
  max_tokens: 100000

task: bin_summarization

nepabench_directory: ./nepabench

benchmark:
  input_file: BinSummarize/benchmark.json
  field_mapping:
    bin: bin
    comments: comments
    summary: summary

evaluation:
  prompt_file: 'prompts/bin_summary.txt'
  continue_previous: true
  eval_kwargs:
    max_attempts: 10
    retry_delay: 20

scoring:
  batch_size: 10
  embed_model_name: 'all-MiniLM-L6-v2'
  metrics:
    - answer_correctness
    - answer_similarity

output:
  directory: 'results/nepabench_tests/summarize_gemini/'
  logfile: 'logs/nepabench_tests/summarize_gemini.log'
